version: '3'

networks:
  springboot-mysql-net:
    driver: bridge      

services:
  mysql-docker-container:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=counter
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=12345
    ports:
      - 3307:3306
    networks:
      - springboot-mysql-net  
      
  spring-boot-container:
    image: ekar-latest:latest
    ports:
      - 8080:8080
    networks:
      - springboot-mysql-net    
    depends_on:
      - mysql-docker-container
      
      
